In [1]:
import numpy as np
from src.dbscan import DBSCAN

In [2]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
glass_identification = fetch_ucirepo(id=42) 
  
# data (as pandas dataframes) 
X = glass_identification.data.features 
y = glass_identification.data.targets 

In [8]:
dbscan = DBSCAN(eps=0.3, min_samples=5)
y_pred = dbscan.fit_predict(X, metric="euclidean")

In [9]:
np.unique(y, return_counts=True)

(array([1, 2, 3, 5, 6, 7]), array([70, 76, 17, 13,  9, 29]))

In [10]:
np.unique(y_pred, return_counts=True)

(array([-1,  0,  1,  2,  3]), array([148,  16,  40,   5,   5]))

In [11]:
import sklearn.cluster

dbscan = sklearn.cluster.DBSCAN(eps=0.3, min_samples=5)
y_pred = dbscan.fit_predict(X)
np.unique(y_pred, return_counts=True)

(array([-1,  0,  1,  2,  3]), array([148,  16,  40,   5,   5]))